Parameters:
  ProjectName:
    Type: String
    Description: Project name to link stacks
    Default: am-multi-account
  SecondaryAccountId:
    Type: String
    Description: Account Id to share resources with

Resources:

  SubnetResourceShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: true
      Name: vpc-share
      Principals:
        - !Ref SecondaryAccountId
      ResourceArns:
        - Fn::Join:
          - '/'
          - - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet'
            - Fn::ImportValue: !Sub '${ProjectName}:PrivateSubnet1'
        - Fn::Join:
          - '/'
          - - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet'
            - Fn::ImportValue: !Sub '${ProjectName}:PrivateSubnet2'
        - Fn::Join:
          - '/'
          - - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet'
            - Fn::ImportValue: !Sub '${ProjectName}:PublicSubnet1'
        - Fn::Join:
          - '/'
          - - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet'
            - Fn::ImportValue: !Sub '${ProjectName}:PublicSubnet2'
