Parameters:
  ProjectName:
    Type: String
    Description: Project name to link stacks
    Default: am-multi-account
  SecondaryAccountId:
    Type: String
    Description: Account Id to share resources with

Resources:
  MeshShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: true
      Name: mesh-share
      Principals:
        - !Ref SecondaryAccountId
      ResourceArns:
         - !Sub 'arn:aws:appmesh:${AWS::Region}:${AWS::AccountId}:mesh/${ProjectName}-mesh'